server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
spring:
  application:
    name: account-service
  info:
    app:
      description: This is account service on spring boot application
      name: Account Service
      version: 1.0.0