server:
  port: 8762
spring:
  application:
    name: zuul-server
  info:
    app:
      description: This is zuul server on spring boot application
      name: Zuul Server
      version: 1.0.0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    auth-admin:
      path: /admin/**
      service-id: auth-service
    auth-login:
      path: /login/**
      service-id: auth-service
    auth-service:
      path: /auth/**
      sensitive-headers: 'Cookie,Set-Cookie '
      service-id: auth-service
      strip-prefix: false
    customer-service:
      path: /customer-service/**
      service-id: customer-service
    account-service:
      path: /account-service/**
      service-id: account-service
management:
  endpoints:
    web:
      exposure:
        include: "*"