server:
  port: 8762
spring:
  application:
    name: zuul-server
  info:
    app:
      description: This is zuul server on spring boot application
      name: Zuul Server
      version: 1.0.0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8762/eureka/
zuul:
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service